### ISSUE TITLE
เพิ่มหน้า Root/Modified

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#1]
## ตัวอย่างการทำงานโดยอ้างอิงจาก StemModified
ไฟล์นี้จะไปอยู่ที่ [/src/pages/Stem/stemModified.md](../blob/69b327b/src/pages/Stem/stemModified.md)

ถ้าจะใส่รูปภาพต้องเพิ่มโค้ดนิดหน่อยที่ไฟล์ [/src/pages/Stem/StemModified.js](../blob/69b327b/src/pages/Stem/StemModified.js)

1. เพิ่มอันนี้ตรงหัวไฟล์ [/src/pages/Stem/StemModified.js](../blob/69b327b/src/pages/Stem/StemModified.js)
`import ชื่อรูปที่จะอ้างอิงในmd from "../../images/ชื่อไฟล์";`
เช่น
`import stemModifiedCorm from "../../images/stemModifiedCorm.jpg";`

2. เพื่ม **ชื่อรูปที่จะอ้างอิงในmd** ใน `images: { }` เช่น
```
const stemModifiedData = {
  markdown: stemModifiedMarkdown,
  images: {
    stemModifiedRhizome,
    stemModifiedTuber,
    stemModifiedBulb,
    stemModifiedCorm
  }
};
```
3. ใส่รูปใน md ตามนี้
`![คำบรรยายรูป](ชื่อรูปที่จะอ้างอิงในmd)`
เช่น
`![Corm](stemModifiedCorm)`

**Comment by mantayonpiam** [comment]
# รากที่เปลี่ยนแปลงไปทำหน้าที่พิเศษ

### รากค้ำจุน (Prop root)
เป็นรากที่แตกออกจากข้อของลำต้นแล้วพุ่งทแยงลงไปในดิน เพื่อช่วยพยุงลำต้นไว้ไม่ให้ล้มง่ายเช่น รากค้ำจุนของข้าวโพด เตย ลำเจียก ยางอินเดีย ไทรย้อย โกงกาง
![Prop](rootModifirdProp)

### รากเกาะ (Climbing root) 
เป็นรากที่มักแตกออกตามข้อของลำต้น แล้วมาเกาะตามหลักหรือเสา เพื่อพยุงลำต้นให้ติดแน่นและชูลำต้นขึ้นที่สูง เช่น รากพลู พลูด่าง พริกไทย กล้วยไม้ และไม้เลื้อยต่างๆ
![Climbing](rootModifiedClimbing)

### รากสังเคราะห์ด้วยแสง (Photosynthesis root)
เป็นรากที่แตกออกจากข้อของลำต้นหรือกิ่งแล้วห้อยลงมาในอากาศ มีสีเขียวของคลอโรฟิลล์จึงเป็นรากที่ทำหน้าที่สังเคราะห์แสงได้ เช่น รากกล้วยไม้ ไทร โกงกาง
![Photosynthesis](rootModifiedPhotosynthesis)

### รากหายใจ (Respiration root) 
ทำหน้าที่ช่วยหายใจได้มากเป็นพิเศษ  รากชนิดนี้จะชูปลายขึ้นมาเหนือดินหรือผิวน้ำ บางทีก็ลอยตามผิวน้ำจึงเรียกอีกชื่อหนึ่งว่ารากทุ่นลอย เช่น ลำพู แสม โกงกาง แพงพวยน้ำ ผักกระเฉด
![Respiration](rootModifiedRespiration)

### รากกาฝาก (Parasitic root) 
เป็นรากของพืชที่เป็นปาราสิต ไปเกาะพืชชนิดอื่นซึ่งเป็น host เพื่อแย่งอาหาร เช่น ต้นกาฝาก ฝอยทอง พืชพวกนี้จะแทงรากเข้าไปใน xylem และ phloem ของ host
![Parasitic](rootModifiedParasitic)

### รากหนาม (Thorn Root) 
เป็นรากที่มีลักษณะเป็นหนามงอกมาจากบริเวณโคนต้น ตอนงอกใหม่ ๆ เป็นรากปกติแต่ต่อมาเกิดเปลือกแข็งทำให้มีลักษณะคล้ายหนามแข็ง ช่วยป้องกันโคนต้นได้ ปกติพบในพืชที่เจริญในที่น้ำท่วมถึง เช่น โกงกาง ส่วนในปาล์มบางชนิดจะปรากฏรากหนามกรณีที่มีรากลอยหรือรากค้ำจุน
![Thorn](rootModifiedThorn)

### รากสะสมอาหาร (Food storage root) 
เป็นรากที่สะสมอาหารพวกแป้งโปรตีนหรือน้ำตาลไว้ จนรากเปลี่ยนแปลงรูปร่างมีขนาดใหญ่ซึ่งมักจะเรียกกันว่า “หัว” เช่น หัวแครอท หัวผักกาด หรือหัวไชเท้า หัวผักกาดแดงหรือแรดิช (Radish) หัว บีท (Beet root) และหัวมันแกว เป็นรากสะสมอาหารที่เปลี่ยนแปลงมาจากราก แก้ว ส่วนรากสะสมอาหารของมันเทศ รักเร่ กระชาย เปลี่ยนแปลงมาจากรากแขนง
![Foodstorage](rootModifiedFoodstorage)

**Comment by mantayonpiam** [comment]
![Prop](rootModifirdProp)
![Climbing](rootModifiedClimbing)
![Photosynthesis](rootModifiedPhotosynthesis)
![Respiration](rootModifiedRespiration)
![Parasitic](rootModifiedParasitic)
![Thorn](rootModifiedThorn)
![Foodstorage](rootModifiedFoodstorage)

**Comment by ThewBear** [comment]
Closed by [commit 4817068](../commit/48170681a1b0b69e7910d2f207ab9ad3e4ac7aee)
