### ISSUE TITLE
แก้ไขและเพิ่มรูป Primary meristem

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#11]
แก้ที่ [หน้าแรกของแอพ](https://thewapp.github.io/Biology-Plant/#/)

## แก้ไขรูปหลักของ Primary Meristem
1. ลบเซลล์บนชั้น Epidermis

## เพิ่มรูปย่อยของ Primary Meristem 3 รูป
1. รูป Protoderm ให้เขียนเน้นเพิ่มว่าพัฒนาต่อเป็น Epidermis
2. รูป Ground meristem ให้เขียนเน้นว่าพัฒนาต่อเป็น Cortex
3. รูป Procambium ให้เขียนเน้นว่า พัฒนาต่อเป็น Stele

**Comment by Sornwarit** [comment]
finish

**Comment by ThewBear** [comment]
Closed by https://github.com/ThewApp/Biology-Plant/commit/586ce9d1e5e833095725673c2e0d7fe84e6b3010
