### ISSUE TITLE
เพิ่มหน้า Tissue/CorkCambium

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#14]
เขียนด้วยว่าพัฒนาไปเป็น Cork กับ Phelloderm

**Comment by mantayonpiam** [comment]
# Cork cambium หรือ Phellogen (เนื้อเยื่อป้องกัน) 
เป็นเนื้อเยื่อเจริญทางด้านข้าง โดยแบ่งเซลล์ออกไปด้านนอกเจริญไปเป็น Cork cell หรือ Phellem เพื่อสร้างเนื้อเยื่อcork และแบ่งเซลล์เข้าด้านในเป็นเนื้อเยื่อ Phelloderm ซึ่งประกอบด้วยเซลล์พาเรงคิมา(parenchyma) เป็นการเจริญเติบโตขั้นที่สอง
![Structure](corkCambiumStructure)

ในรากพืชใบเลี้ยงคู่เนื้อเยื่อบริเวณเพอริไซเคิล (Pericycle) เปลี่ยนสภาพมาเป็นคอร์กแคมเบียม (Cork cambium) แล้วสร้างเนื้อเยื่อคอร์กแทนเนื้อเยื่อผิวเดิม


ชั้นเซลล์ที่รวมตั้งแต่ cork ชั้นนอกสุดจนถึงชั้นphelloderm เรียกว่า **periderm** เป็นองค์ประกอบส่วนหนึ่งของเปลือก
![Cork](corkCambiumCork)
![Phelloderm](corkCambiumPhelloderm)
![Periderm](corkCambiumPeriderm)

## บริเวณที่พบ
ใต้ผิวชั้นนอกของรากและลำต้น

## หน้าที่ Cork cambium
สร้างส่วนหนึ่งของเปลือกไม้ แบ่งเซลล์เพื่อสร้างเนื้อเยื่อ (cork หรือ phellem ) ให้มาทำหน้าที่ป้องกันอันตรายและความเสียหายแทนเนื้อเยื่อผิวนอก (epidermis) ที่ใกล้หมดอายุ

**Comment by ThewBear** [comment]
เขียนงงๆนะ แก้ใหม่ @mantayonpiam

**Comment by ThewBear** [comment]
Closed by https://github.com/ThewApp/Biology-Plant/commit/d959d0c5ffbd5e2a0596d744a157db1e221174ae
