### ISSUE TITLE
เพิ่มหน้า Tissue/VascularCambium

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#15]
เขียนด้วยว่าพัฒนาไปเป็น 2° Xylem กับ 2° Phloem

**Comment by mantayonpiam** [comment]
#  Vascular Cambium
เกิดจากการเปลี่ยนสภาพมาจากเนื้อเยื่อระหว่าง xylem ขั้นที่ 1 กับ phloem ขั้นที่ 1
![Structure](vascularCambiumStructure)

## บริเวณที่พบ
ระหว่างเนื้อเยื่อลำเลียงน้ำและแร่ธาตุ (Xylem) และ เนื้อเยื่อลำเลียงอาหาร (Phloem) 

## หน้าที่ Vascular Cambium
สร้างท่อลำเลียงระยะทุติยภูมิ (secondary growth) โดยเซลล์ที่มีการแบ่งเซลล์เข้ามาด้านในลำต้นจะเจริญเป็น secondary xylem ส่วนเซลล์ที่มีการแบ่งเซลล์ออกด้านนอกของลำต้นจะเจริญเป็น secondary phloem  โดยปกติการแบ่งเซลล์เพื่อสร้าง secondary xylem จะเกิดขึ้นเร็วกว่า secondary phloem  ดังนั้นจึงพบ secondary xylem เป็นส่วนหลักของเนื้อไม้
![SecondaryXylem](vascularCambiumSecondaryXylem)
![SecondaryPhloem](vascularCambiumSecondaryPhloem)

**วงปี (Annual ring)** เป็นส่วนของ secondary xylem สามารถใช้ในการคาดคะเนอายุของไม้ยืนต้นได้ ใน 1 รอบวงปี จะแบ่งออกเป็น 2 ส่วน คือ
1. summer wood หรือ late wood เป็น secondary xylem ที่เจริญในช่วงที่น้ำน้อย เซลล์มีขนาดเล็ก แถบที่เกิดขึ้นจะมีสีเข้มค่อนข้างแคบ 
2. Spring wood หรือ early wood เป็น secondary xylem ที่เจริญในช่วงที่น้ำมาก เซลล์มีขนาดใหญ้แถบที่เกิดขึ้นจะมีสีจางค่อนข้างกว้าง
![AnnualRing](vascularCambiumAnnualRing)

**Comment by ThewBear** [comment]
Closed by https://github.com/ThewApp/Biology-Plant/commit/052b9ca5b0f73d72f10ee8b6de0161a5b28f38d5 and Hotfix https://github.com/ThewApp/Biology-Plant/commit/c5e3133cf9add5f06c61b0d7eb2a0ba6ace392d4
