### ISSUE TITLE
เพิ่มหน้า Tissue/Pericycle

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#17]

**Comment by mantayonpiam** [comment]
# Pericycle
เป็นเซลล์ผนังบางขนาดเล็ก  มีความหนาเพียง 1-2 ชั้นของเซลล์ ในพืชบางชนิดสังเกตเห็นได้ง่ายแต่บางชนิดสังเกตเห็นได้ยาก เซลล์ในชั้นนี้อาจจะแปรสภาพกลับกลายเป็นเนื้อเยื่อเจริญ
![Structure](pericycleStructure)

## บริเวณที่พบ
เป็นเนื้อเยื่อที่อยู่ถัดจาก endodermis เข้าไป

## หน้าที่ Pericycle
แบ่งเซลล์ให้เกิดเป็นรากแขนง (lateral root) และในรากที่มีอายุมากขึ้นอาจจะเปลี่ยนแปลงไปเป็น vascular cambium และ cork cambium
![LateralRoot](pericycleLateralRoot)

**Comment by ThewBear** [comment]
Closed by https://github.com/ThewApp/Biology-Plant/commit/1d547170902410def79928db1cc80bdacf9573f6
