### ISSUE TITLE
เพิ่มหน้า Root/Type

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#18]
ชนิดของราก พวก

* Primary root
* Secondary root
* Adventitious root

**ใส่รูปด้วย**

**Comment by mantayonpiam** [comment]
# ชนิดของรากเมื่อจำแนกตามการกำเนิด

## Primary root 
เป็นรากที่มีกำเนิดและเจริญเติบโตมาจาก radicle รากชนิดนี้มักจะพุ่งดิ่งลงสู่ดินไปเรื่อยๆ ตอนโคนจะโตและค่อยๆเรียวเล็กไปจนถึงปลาย หน้าที่ส่วนใหญ่ใช้สำหรับเป็นหลักรับส่วนอื่นๆของพืชให้ทรงตัวอยู่ได้ จึงเรียกว่า รากแก้ว (Tap root) ซึ่งจะยาวและใหญ่กว่ารากอื่นๆทั้งหมด
![PrimaryRoot](rootTypePrimaryRoot)

## Secondary root 
เป็นรากที่มีกำเนิดและเจริญเติบโตมาจาก Primary root เป็นรากที่เรียกว่ารากแขนง (lateral root or branch root) มักจะออกเฉียงลงไปในดินจนเกือบขนานไปกับพื้นดิน รากชนิดนี้อาจแตกแขนงออกเป็นทอดๆ มีกำเนิดออกมาจากเนื้อเยื่อ pericycle ในรากเดิม
![SecondaryRoot](rootTypeSecondaryRoot)

## Adventitious root 
เป็นรากที่ไม่ได้มีกำเนิดมาจาก radicle และไม่เป็นแขนงของ primary root นิยมเรียกว่า รากวิสามัญ อาจแตกออกตามโคนต้นของพืช ตามข้อของลำต้นหรือกิ่ง ตามใบ หรือจากกิ่งตอน เช่น 
- รากฝอย (Fibrous root) เป็นรากเส้นเล็กมากมาย ขนาดโตสม่ำเสมอกัน งอกออกจากรอบๆโคนต้น
พบในพืชใบเลี้ยงเดี่ยวเป็นส่วนใหญ่ เช่น รากข้าว ข้าวโพด  หญ้า หมาก มะพร้าว ตาล กระชาย และในพืชใบเลี้ยงคู่บางชนิด เช่น รากต้อยติ่ง มันเทศ มันแกว มันสำปะหลัง รักเร่ ถั่วพู
![FibrousRoot](rootTypeFibrousRoot]
- รากค้ำจุน (Prop root)
- รากเกาะ (Climbing root)
- รากสังเคราะห์ด้วยแสง (Photosynthesis root)
- รากค้ำจุน (Prop root)
- รากเกาะ (Climbing root) 
- รากสังเคราะห์ด้วยแสง (Photosynthesis root)
- รากหายใจ (Respiration root)
- รากกาฝาก (Parasitic root)

**Comment by ThewBear** [comment]
Closed by https://github.com/ThewApp/Biology-Plant/commit/e60762fa30127f6bfd44b2e3a731661037eba5b2
