### ISSUE TITLE
เพิ่มหน้า Tissue/Collenchyma

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#19]

**Comment by mantayonpiam** [comment]
# Collenchyma
ประกอบด้วยเซลล์คอลเลนไคมา(collenchyma cell) มีลักษณะคล้ายกับเซลล์พาเรนไคมา คือมีชีวิตแต่ primary cell wall มีความหนาบางไม่สม่ำเสมอทั่วทั้งเซลล์ เช่น 
- หนารอบๆ เซลล์ เรียกว่า Larmella-collenchyma 
- หนาตามมุมของเซลล์มากกว่าบริเวณอื่นๆ เรียกว่า Angular collenchyma 
- หนาตามช่องว่างระหว่างเซลล์ เรียกว่า Larcunar collenchyma 
เซลล์คอลเลนไคมาสามารถยืดตัวได้เมื่อพืชมีการเจริญเติบโตปฐมภูมิ หรือขยายขนาด
![Structure](collenchymaStructure)
![Larmella](collenchymaLarmella)
![Angular](collenchymaAngular)
![Larcunar](collenchymaLarcunar)

## บริเวณที่พบ
ปกติไม่พบในราก แต่มักพบในลำต้น ก้านใบและแผ่นใบ มักพบอยู่เป็นกลุ่มหรือเป็นมัดถัดเข้ามาจากชั้นเนื้อเยื่อผิว 

## หน้าที่ Collenchyma
ให้ความแข็งแรงแก่ส่วนที่ยังอ่อนของพืช

**Comment by ThewBear** [comment]
Closed by https://github.com/ThewApp/Biology-Plant/commit/260eb9ec7a6079ecc87cbbff6d7ba2aa1dffd0d1
