### ISSUE TITLE
เพิ่มหน้า Leaf/Modified

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#2]

**Comment by mantayonpiam** [comment]
# ใบที่เปลี่ยนแปลงไปทำหน้าที่พิเศษ

### Leaf tendril 
ใบที่เปลี่ยนแปลงไปเป็นมือเกาะเพื่อยึดลำต้นหรือพยุงลำต้น เช่น ตำลึง มะระ ถั่วลันเตา 
![Tendril](leafModifiedTendril)

### Leaf spine 
ใบที่เปลี่ยนแปลงไปเป็นหนามเพื่อป้องกันอันตรายจากศัตรูหรือสัตว์ที่จะมาทำร้าย รวมทั้งป้องกันการระเหยของน้ำ เช่น กระบองเพชร ใบเหงือกปลาหมอ ใบสับปะรด 
![Spine](leafModifiedSpine)

### Storage leaf 
ใบที่เปลี่ยนแปลงเพื่อทำหน้าที่เก็บสะสมอาหารหรือน้ำ ใบประเภทนี้จะอวบอ้วน เช่น ใบว่านหางจระเข้ เป็นต้น
![Storage](leafModifiedStorage)

### Scale leaf  
ใบที่เปลี่ยนแปลงไปเป็นเกล็ดเล็กๆ  มักไม่มีคลอโรฟีลล์จึงไม่ทำหน้าที่สังเคราะห์ด้วยแสง  เช่น  ใบเกล็ดของข่า  ขิง  เผือก  แห้วจีน เป็นต้น บางชนิดทำหน้าที่สะสมอาหาร  เช่นใบเกล็ดในหัวหอม  บางชนิดทำหน้าที่คุ้มครองตาอ่อน (bud scale)
![Scale](leafModifiedScale)

### Phyllode  
ส่วนต่างๆของใบ เช่น ก้านใบ เปลี่ยนแปลงไปเป็นแผ่นแบนคล้ายตัวใบ  แต่ทว่าแข็ง พืชที่มีใบแบบนี้จึงมักไม่มีตัวใบที่แท้จริง  เช่น  ใบกระถินณรงค์  เปลี่ยนแปลงมาจากก้านใบ 
![Phyllode](leafModifiedPhyllode)

### Floating leaf 
ส่วนของก้านใบ (petiole) พองออกเพื่อใช้ในการลอยน้ำ  เช่น  ผักตบชวา 
![Floating](leafModifiedFloating)

### Vegetative reproduction organ
ใบที่เปลี่ยนแปลงไปเพื่อช่วยในการแพร่พันธุ์หรือขยายพันธุ์ เช่น  ใบของคว่ำตายหงายเป็น  เศรษฐีพันล้าน 
![Reproduction](leafModifiedReproduction)

### Carnivorous leaf / Insectivorous leaf
ใบที่เปลี่ยนแปลงไปเป็นกับดักแมลงหรือสัตว์เล็กๆ เช่น  ต้นหม้อข้าวหม้อแกงลิง  กาบหอยแครง  หยาดน้ำค้าง สาหร่ายข้าวเหนียว
![Carnivorous](leafModifiedCarnivorous)

**Comment by mantayonpiam** [comment]
![Tendril](leafModifiedTendril)
![Spine](leafModifiedSpine)
![Storage](leafModifiedStorage)
![Scale](leafModifiedScale)
![Phyllode](leafModifiedPhyllode)
![Floating](leafModifiedFloating)
![Reproduction](leafModifiedReproduction)
![Carnivorous](leafModifiedCarnivorous)

**Comment by ThewBear** [comment]
Closed by [commit da011c2](../commit/da011c2936338dbb6542d3f29ae73c86611f5340)
