### ISSUE TITLE
เพิ่มหน้า Tissue/Cork

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#21]
บอกด้วยว่าสร้างมาจาก Cork cambium

**Comment by mantayonpiam** [comment]
# Cork หรือ phellem
เกิดจากการแบ่งตัวของคอร์กแคมเบียม(cork cambium) หรือเฟลโลเจน (Phellogen)  เมื่อคอร์กเติบโตเต็มที่แล้วจะตาย โดยโพรโทพลาสซึมและเยื่อหุ้มเซลล์สลายไปเหลือเฉพาะผนังเซลล์ที่มีซูเบอริน  และคิวติเคิลสะสมซึ่งน้ำจะไม่สามารถผ่านได้  เรียกเนื้อเยื่อชั้นคอร์กรวมกับเฟลโลเจนและเฟลโลเดิร์มว่า เพอริเดิร์ม (Periderm)
![Structure](corkStructure)
![Periderm](corkPeriderm)

**Comment by ThewBear** [comment]
Closed by https://github.com/ThewApp/Biology-Plant/commit/e6b2c9f9ae2347b80a8407394e0ab1999482d18b
