### ISSUE TITLE
เพิ่มหน้า Tissue/Mesophyll

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#22]
ลองดู
* https://thewapp.github.io/Biology-Plant/#/leaf/view
* https://thewapp.github.io/Biology-Plant/#/leaf/compare

ต้องมี Palisade Spongy และ พืช C4

**Comment by mantayonpiam** [comment]
# Mesophyll 
เป็นเนื้อเยื่อที่อยู่ระหว่างชั้น epidermis ทั้งสองด้านส่วนใหญ่เป็นเนื้อเยื่อพวก parenchyma โดยมี parenchyma cell ที่มีลักษณะแตกต่างกัน 2 แบบ คือ
![Structure](mesophyllStructure)

## Palisade mesophyll / Palisase parenchyma 
เป็นเนื้อเยื่อพาเรนไคมาที่รูปร่างยาวเรียงตัวตั้งฉากกับชั้นเอพิเดอร์มิส ส่วนใหญ่อยู่ทางด้าน  upper epidermis  อาจมีชั้นเดียวหรือหลายชั้นก็ได้ ภายในเซลล์ palisade cell มีคลอโรพลาสต์อยู่มากจึงมีบทบาทสำคัญในการสังเคราะห์ด้วยแสง 
![Palisade](mesophyllPalisade)

## Spongy mesophyll / Spongy parenchyma 
เป็นเนื้อเยื่อพาเรนไคมาที่มีรูปร่างกลม เรียงตัวอยู่อย่างหลวมๆใต้ชั้น palisade mesophyll มีช่องว่างมาก แต่มีคลอโรพลาสต์น้อยกว่า
![Spongy](mesophyllSpongy)

ในพืชใบเลี้ยงเดี่ยวชั้น mesophyll จะมีรูปร่างของเซลล์พาเรนไคมาเหมือนกันทั้งชั้น ไม่แยกเป็น palisade และ spongy 

**พืช C3** ได้แก่ ข้าว ข้าวสาลี ถั่ว เป็นต้น 
โครงสร้างภายในของใบจะประกอบด้วย mesophyll cell 2 แบบ คือ palisade mesophyll และ spongy mesophyll และมีกลุ่มเนื้อเยื่อลำเลียงแทรกอยู่ อาจมีกลุ่มเซลล์ล้อมรอบกลุ่มท่อลำเลียง ซึ่งเรียกว่า bundle sheath cell หรือไม่ก็ได้
![C3](mesophyllC3)

 **พืช C4** มักเป็นพืชที่มีถิ่นกำเนิดในเขตศูนย์สูตร เช่น ข้าวโพด อ้อย และบานไม่รู้โรย
ประกอบด้วย mesophyll cell ชนิดเดียวกระจายรอบๆ โครงสร้างภายในของใบที่เด่นชัดคือ จะมี bundle sheath cells ที่มีคลอโรพลาสต์ล้อมรอบกลุ่มท่อลำเลียง
![C4](mesophyllC4)

**Comment by ThewBear** [comment]
Closed by https://github.com/ThewApp/Biology-Plant/commit/26142e3816b4f7f418dbd681f8cb416d19b9a0ff
