### ISSUE TITLE
เพิ่มหน้า Tissue/BundleSheath

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#23]
ลองดู
* https://thewapp.github.io/Biology-Plant/#/leaf/view
* https://thewapp.github.io/Biology-Plant/#/leaf/compare

ต้องมี พืช C3 และ C4

**Comment by mantayonpiam** [comment]
# Bundle Sheath
กลุ่มเซลล์ที่อยู่รอบๆมัดท่อลำเลียงของพืช มักเป็นเซลล์พวกพาเรงคิมาเรียงตัวกัน 1 – 2 ชั้น รอบมัดท่อลำเลียง
ในพืช C3 อาจจะพบ Bundle Sheath หรือไม่ก็ได้ แต่ในพืช C4 จะพบ Bundle sheath cell ที่มีคลอโรพลาสต์ล้อมรอบกลุ่มท่อลำเลียง
![Structure](bundleSheathStructure)
![C3](bundleSheathC3)
![C4](bundleSheathC4)

**Comment by ThewBear** [comment]
Closed by https://github.com/ThewApp/Biology-Plant/commit/9dbf9cf2e1edff5379c0ed3a2b834c85609525c9
