### ISSUE TITLE
เพิ่มหน้า Tissue/Epidermis

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#3]

**Comment by mantayonpiam** [comment]
# เนื้อเยื่อพืช (Plant Tissue)
หมายถึง กลุ่มเซลล์พืชที่อยู่รวมกัน มีลักษณะเหมือนกัน และร่วมทำหน้าที่เฉพาะ ประเภทเดียวกัน

# ประเภทของเนื้อเยื่อพืชจำแนกตามตำแหน่งและหน้าที่

## ระบบเนื้อเยื่อผิว (Dermal tissue system) 
เนื้อเยื่อที่อยู่ด้านนอกสุดของโครงสร้างต่างๆ ของพืชประกอบด้วยเนื้อเยื่อ 2 ชนิด คือ 
### เอพิเดอร์มิส (Epidermis) 
พบในการเจริญระยะ primary growth ของพืชประกอบด้วย epidermal cell ซึ่งเป็นเซลล์มีชีวิตอยู่
### คอร์ก(Cork) 
พบในการเจริญระยะ secondary growth ประกอบด้วย cork cell ซึ่งเป็นเซลล์ที่ตายแล้ว จึงมี lumen และมีสารชนิด suberin สะสมมากที่ cell wall

## ระบบเนื้อเยื่อลำเลียง (Vascular tissue system) 
เนื้อเยื่อที่ทำหน้าที่ลำเลียงน้ำ และอาหาร
### ไซเลม (Xylem) 
เนื้อเยื่อลำเลียงน้ำ ประกอบด้วยเซลล์ 4 ชนิดคือ Tracheid, Vessel member, Xylem parenchyma และ Xylem fiber
### โฟลเอม(Phloem) 
เนื้อเยื่อลำเลียงอาหาร ประกอบด้วยเซลล์ 4 ชนิดคือ Sieve tube member, Companion cell, Phloem parenchyma และ Phloem fiber
** ในพืชใบเลี้ยงคู่จะมี Vascular cambium คั่นกลางระหว่าง xylem กับ phloem

## ระบบเนื้อเยื่อพื้น (Ground tissue system)
เนื้อเยื่อหลักที่เป็นส่วนประกอบพื้นฐานของส่วนต่างๆ ของต้นพืชประกอบด้วยเนื้อเยื่อ 3 ชนิด
### พาเรงไคมา (Parenchyma) 
เป็นเซลล์ที่มีชีวิต พบในราก ลำต้น ก้านใบ และใบ อาจมี chloroplast 
### คอลเลงไคมา (Collenchyma) 
เป็นเซลล์ที่มีชีวิต พบในลำต้นบริเวณถัดจาก epidermis เข้าไป ผนังหนากว่า parenchyma แต่ไม่สม่ำเสมอ ช่วยเสริมความแข็งแรง
### สเกลอเรงไคมา (Sclerenchyma) 
ประกอบด้วยเซลล์ที่ไม่มีชีวิต ผนังหนามีสาร lignin มี lumen และ pit แบ่งเป็น 2 ชนิดคือ
 1) ไฟเบอร์ (fiber) เซลล์เป็นเหลี่ยมชัดเจน ยาว และ pit ไม่แตกแขนง  
 2) สเคอริด (Sclereid) เซลล์ไม่เป็นเหลี่ยม สั้น มีหลากหลายรูปแบบ และ pit มีการแตกแขนง พบในชั้นcortex ของรากพืชใบเลี้ยงเดี่ยว แทรกอยู่ในลำต้น และระบบเนื้อเยื่อลำเลียง bundle sheath และเนื้อผลไม้

# ประเภทของเนื้อเยื่อพืชจำแนกตามคุณสมบัติของการแบ่งเซลล์

## เนื้อเยื่อเจริญ (meristematic tissue)
ประกอบด้วยเซลล์เจริญ (meristematic cell) ซึ่งเป็นเซลล์ที่คงคุณสมบัติของการแบ่งเซลล์แบบ mitosis ไว้ตลอดชีวิต ทำให้พืชมีการเจริญเติบโตได้อย่างไม่มีที่สิ้นสุดตราบเท่าที่พืชยังมีชีวิต ดังนั้นเราจึงสังเกตเห็นได้ว่าลำต้นพืช รวมทั้งราก สามารถเจริญเติบโต ยืดยาว หรือแผ่กิ่งก้านหรือสาขาออกไปได้เรื่อยๆ หรือมีขนาดเส้นผ่านศูนย์กลางเพิ่มขึ้นเมื่อพืชมีอายุมากขึ้นเรื่อยๆซึ่งเป็นลักษณะที่ไม่พบในสัตว์ ที่มีการเจริญเติบโตมักจะหยุดหรือสิ้นสุดลงเมื่อสัตว์มีอายุถึงในระดับหนึ่ง แบ่งได้เป็น 3 แบบใหญ่ๆ คือ 	
### เนื้อเยื่อเจริญส่วนปลาย (apical meristem)
เนื้อเยื่อเจริญส่วนปลายที่พบตามปลายยอดของลำต้นหรือกิ่งก้านเรียก เนื้อเยื่อเจริญปลายยอด (apicalshoot meristem) แต่ถ้าพบที่ปลายราก เรียกว่า เนื้อเยื่อเจริญปลายราก (apical root meristem) ทั้งเนื้อเยื่อเจริญปลายยอดและปลายราก จะสร้างเนื้อเยื่อเจริญอีกชุดหนึ่งที่เรียกว่า เนื้อเยื่อเจริญปฐมภูมิ (primarymeristem) ขึ้นมา ซึ่งเนื้อเยื่อเจริญปฐมภูมิยังแบ่งได้ออก 3 กลุ่ม คือ โพรโตเดิร์ม (protoderm) โพรแคมเบียม (procambium) และกราวด์เมอริสเต็ม (ground meristem) 
เนื้อเยื่อเจริญปฐมภูมิทั้ง 3 กลุ่มจะพัฒนาและเปลี่ยนแปลงต่อไปเป็นเนื้อเยื่อถาวรชนิดต่างๆ การเจริญเติบโตของอวัยวะหรือส่วนต่างๆ ของพืชที่มาจากการทำงานของเนื้อเยื่อเจริญส่วนปลาย หรือ เนื้อเยื่อเจริญปฐมภูมิ เรียกว่า การเจริญเติบโตปฐมภูมิ (primary growth) ซึ่งเป็นการเจริญเติบโตที่ทำให้ส่วนต่างๆ ของพืชมีความสูง หรือความยาวเพิ่มมากขึ้น

### เนื้อเยื่อเจริญเหนือข้อ (Intercalary Meristem)
อยู่บริเวณข้อของลำต้น (เมื่อยังอ่อนๆ อยู่) หรือบริเวณเหนือข้อ (โคนปล้อง)ของลำต้น (เมื่อโตแล้ว) ของพืชใบเลี้ยงเดี่ยว เป็นส่วนใหญ่ มีหน้าที่ช่วยให้ปล้องเจริญยืดยาวออกไป เนื้อเยื่อเจริญชนิดนี้ ความจริงแล้วก็เป็น Apicalmeristem นั่นเอง แต่ยังคงมีลักษณะเป็นเนื้อเยื่อเจริญอยู่ แม้ว่าส่วนเหนือขึ้นไปจะเปลี่ยนแปลงไปเป็นเนื้อเยื่อถาวรแล้วก็ตาม

### เนื้อเยื่อเจริญด้านข้าง (lateral meristem)
ในขณะที่เนื้อเยื่อเจริญส่วนปลายนั้นเกิดขึ้นมาตั้งแต่พืชอยู่ในระยะเอ็มบริโอ (embryo) เนื้อเยื่อเจริญด้านข้างจะเป็นเนื้อเยื่อเจริญที่เกิดหรือพัฒนาขึ้นมาภายหลัง และไม่ได้พบในพืชทุกชนิด 
เนื้อเยื่อเจริญด้านข้างแบ่งได้เป็น 2 กลุ่ม คือ
1) แคมเบียมท่อลำเลียง (vascular cambium) 
2) คอร์กแคมเบียม (cork cambium) หรือ Phellogen
การเจริญเติบโตของลำต้น หรือราก ที่มาจากการทำงานหรือการแบ่งเซลล์ของเนื้อเยื่อเจริญด้านข้าง เรียกว่า การเจริญเติบโตทุติยภูมิ (secondary growth) ซึ่งเป็นการเจริญเติบโตที่ทำให้ลำต้น หรือรากของพืชมีขนาดเส้นผ่านศูนย์กลางหรือเส้นรอบวงเพิ่มมากขึ้น ซึ่งการเจริญเติบโตทุติยภูมินั้นจะพบได้เฉพาะในพืชที่มีการสร้างเนื้อเยื่อเจริญด้านข้าง พืชที่ไม่มีการสร้างเนื้อเยื่อเจริญด้านข้าง จะไม่มีการเจริญเติบโตทุติยภูมิ

## เนื้อเยื่อถาวร (permanent tissue)
เป็นเนื้อเยื่อที่เมื่อเซลล์พัฒนาไปเต็มที่แล้ว โดยปกติจะไม่มีการแบ่งเซลล์อีก เนื้อเยื่อถาวรมีหลายชนิด  แต่ละชนิดพัฒนาและเปลี่ยนสภาพ (differentiation) มาจากเนื้อเยื่อเจริญ 
เนื้อเยื่อถาวรแบ่งออกไปเป็น 2 ประเภท คือ

### เนื้อเยื่อถาวรเชิงเดี่ยว (Simple permanent tissue ) เป็นเนื้อเยื่อที่เกิดจากเซลล์ถาวรชนิดเดียวกันมาอยู่ร่วมกันและทำหน้าที่ร่วมกัน มีหลายชนิด ดังนี้ 

1. อิพิเดอร์มิส ( Epidermis)
เป็นเนื้อเยื่อชั้นผิวนอกสุดของส่วนต่าง ๆ ของพืชที่อายุน้อย ทำหน้าที่ป้องกันเซลล์ที่อยู่ด้านในต้นพืชประกอบด้วยเซลล์ที่เรียงตัวชิดกันแน่นจนไม่มีช่องว่างระหว่างเซลล์ ผนังเซลล์ชั้นนอกมีสารคิวทินซึ่งเป็นสารจำพวกขี้ผึ้งฉาบอยู่ เรียกชั้นนี้ว่า ชั้นเคลือบผิวพืช หรือคิวทิเคิล (cuticle) ทำหน้าที่ป้องกันการระเหยนํ้า รักษาความชื้นของเนื้อเยื่อที่อยู่ภายใน ให้ความแข็งแรงแก่พืชและป้องกันเนื้อเยื่อภายในไม่ให้ได้รับอันตราย 
พืชส่วนใหญ่จะมีเอพิเดอร์มิสเพียงชั้นเดียว เอพิเดอร์มิสอาจเปลี่ยนแปลงรูปร่างไปเพื่อทำหน้าที่พิเศษเฉพาะอย่าง ได้แก่ เปลี่ยนไปเป็นขนราก(root hair) ทำหน้าที่ช่วยดูดน้ำและธาตุอาหาร เปลี่ยนไปเป็นขน (trichome) หรือต่อม (gland) ต่าง ๆ เซลล์เอพิเดอร์มิสบริเวณผิวใบด้านล่างหรือผิวลำต้นที่อายุน้อยจะเปลี่ยนไปเป็นเซลล์คุม (guard cell) ทำหน้าที่ควบคุมการปิด-เปิด ของปากใบ (stoma) เซลล์เอพิเดอร์มิสไม่มีคลอโรฟีลล์ยกเว้นในเซลล์คุม ดังนั้นเซลล์คุมจึงสามารถสังเคราะห์ด้วยแสงได้

2. พาเรนไคมา (Parenchyma)
เป็นเนื้อเยื่อพื้นฐานที่สามารถพบได้ทั่วไปในเกือบทุกส่วนของพืช มักจะพบช่องว่างระหว่างเซลล์ (intercellular space) ปรากฏอยู่ภายในเนื้อเยื่อเสมอ เนื้อเยื่อพาเรนไคมาประกอบด้วยเซลล์พาเรนไคมา (parenchyma cell) ซึ่งเป็นเซลล์ที่มีชีวิต มีแวคิวโอล (vacuole) ขนาดใหญ่ โดยทั่วไปมีผนังเซลล์ปฐมภูมิ (primary cell wall) ที่บางและมีความหนาของผนังเซลล์สม่ำเสมอทั่วทั้งเซลล์ 
พาเรนคิมา มีหน้าที่แตกต่างกันไปขึ้นกับส่วนของพืช ส่วนใหญ่แล้วจะทำหน้าที่สะสมสารต่างๆ โดยเรียกชื่อพาเรนไคมาต่างกันตามหน้าที่ เช่น	
chlorenchyma เป็น พาเรนไคมาที่มีคลอโรพลาส ทำหน้าที่ช่วยในกระบวนการสังเคราะห์ด้วยแสง
Aerenchyma เป็น พาเรนไคมาที่ทำหน้าที่เกี่ยวข้องกับการสะสมอากาศ โดยเฉพาะพืชน้ำ

3. คอลเลนไคมา ( Collenchyma)
เป็นเนื้อเยื่อที่ให้ความแข็งแรงแก่ส่วนที่ยังอ่อนของพืช ปกติไม่พบในราก แต่มักพบในลำต้น ก้านใบและแผ่นใบ มักพบอยู่เป็นกลุ่มหรือเป็นมัดถัดเข้ามาจากชั้นเนื้อเยื่อผิว ประกอบด้วยเซลล์คอลเลนไคมา(collenchyma cell) ซึ่งมีลักษณะคล้ายกับเซลล์พาเรนไคมา กล่าวคือมีชีวิต แต่ primary cell wall ของเซลล์คอลเลนไคมานั้น มีความหนาบางไม่สม่ำเสมอทั่วทั้งเซลล์ เช่น หนารอบๆ เซลล์ เรียกว่า Larmella-collenchyma หนาตามมุมของเซลล์มากกว่าบริเวณอื่นๆ เรียกว่า Angular collenchyma หรือ หนาตามช่องว่างระหว่างเซลล์ เรียกว่า Larcunar collenchyma เซลล์คอลเลนไคมาสามารถยืดตัวได้เมื่อพืชมีการเจริญเติบโตปฐมภูมิ หรือขยายขนาด

4. สเกลอเรงคิมา (Sclerenchyma)
สเกลอเรงคิมาเป็นเนื้อเยื่อที่ประกอบด้วยเซลล์ที่มีผนังหนา ส่วนใหญ่เป็นแบบผนังเซลล์ทุติยภูมิ(secondary cell wall)  มีเซลลูโลสและลิกนินมากทำให้เพิ่มความแข็งแรงแก่พืช เซลล์เมื่อโตเต็มที่จะตาย โดยผนังเซลล์ยังอยู่แต่โพรโทพลาสต์สลายไปเหลือเป็นช่องว่าง เรียกว่า ลูเมน (lumen) 
สเกลอเรงคิมาจำแนกได้เป็น 2 ชนิด ได้แก่
       1) ไฟเบอร์ (fiber) หรือเซลล์เส้นใย 
เป็นเซลล์ที่มีรูปร่างเล็กเรียวยาว หัวท้ายแหลม ผนังเซลล์หนามากเพราะมีลิกนินและเซลลูโลสมาสะสม แต่มีความเหนียวและยืดหยุ่น ทำหน้าที่ให้ความแข็งแรงแก่พืช พบอยู่ตามส่วนต่างๆ ของพืช เช่น คอร์เทกช์ ปะปนอยู่ในท่อลำเลียงหรืออยู่โดยรอบท่อลำเลียง มีประโยชน์มากในทางเศรษฐกิจ โดยใช้ทำเป็นเชือก กระดาษ ทอเป็นเสื้อผ้าและกระสอบ 
       2) สเกลอรีด (sclereid) หรือ Stone cell)            
เป็นเซลล์ที่มีลักษณะคล้ายไฟเบอร์แต่ละเซลล์สั้นกว่า รูปร่างมีหลายแบบ ทั้งรูปกลมหลายเหลี่ยม เป็นท่อนยาวหรือเป็นแฉกคล้ายดาว ผนังเซลล์หนามากเนื่องจากมีลิกนินมาสะสม พบในส่วนของพืชที่แข็ง เช่น เปลือกของเมล็ดหรือผลไม้ ได้แก่ กะลามะพร้าว เมล็ดพุทรา เนื้อผลไม้ที่สก เช่น ละมุดน้อยหน่า ฝรั่ง ท้อ สาลี่ อาจพบแทรกในชั้นคอร์เทกซ์ ในท่อลำเลียงของลำต้น ในส่วนของใบและก้านใบ เป็นต้น ทำหน้าที่เพิ่มความแข็งแรงให้แก่ส่วนต่าง ๆของพืช
ลักษณะโดยทั่วไปของเซลล์ทั้งสองชนิดจะแตกต่างกัน คือเซลล์ไฟเบอร์มักมีรูปร่างเซลล์ผอม ยาว ในผนังเซลล์ทุติยภูมิมีรอยเว้าไม่มีขอบ (simple pit) จำนวนน้อย โดยปกติมักพบเพียงหนึ่งหรือสองแนวเท่านั้น   ส่วนสเกลอรีดนั้นมีรูปร่างแตกต่างกันไปมากมาย แต่มักจะไม่เรียวยาวเหมือนเซลล์ไฟเบอร์ และพบรอยเว้าไม่มีขอบจำนวนมากและเป็น รอยเว้าไม่มีขอบที่มักแตกแขนงหรือแยกสาขาด้วย รอยเว้า (pit) คือ รอยบางที่เกิดขึ้นบนผนังเซลล์ทุติยภูมิ เนื่องจากเป็นบริเวณที่ไม่มีการสะสมสารพวกลิกนิน

5. คอร์ก Cork หรือ phellem
เกิดจากการแบ่งตัวของคอร์กแคมเบียม(cork cambium) หรือ เฟลโลเจน (Phellogen)  เมื่อคอร์กเติบโตเต็มที่แล้วจะตาย โดยโพรโทพลาสซึมและเยื่อหุ้มเซลล์สลายไป  เหลือเฉพาะผนังเซลล์ที่มีซูเบอริน  และคิวติเคิลสะสมซึ่งน้ำจะไม่สามารถผ่านได้  เรียกเนื้อเยื่อชั้นคอร์กรวมกับเฟลโลเจน และ เฟลโลเดิร์ม ว่า เพอริเดิร์ม  (Peridrem)

6. เอนโดเดอร์มิส (Endodermis)
เป็นเนื้อเยื่อที่พบในราก อยู่ชั้นในสุดของคอร์เทกซ์เป็นเซลล์ที่มีความหนาเพียงชั้นเดียวในขณะที่รากยังอ่อนผนังเซลล์  เอนโดเดอร์มิสจะบางแต่เมื่อเซลล์อายุมากขึ้นจะมีผนังหนาและมีสารซูเบอริน (suberin)หรือลิกนิน(lignin) มาเกาะตามขวางของเซลล์ เกิดเป็นแถบหนา ๆเป็นแนวรอบเซลล์ตามแนวขวาง (transverse wall) หรือแนวรัศมี (radial wall) เรียกว่า แถบแคสพาเรียน (Casparian strip) 

### เนื้อเยื่อถาวรเชิงซ้อน (complex permanent tissue) 
เป็นเนื้อเยื่อที่ประกอบด้วยกลุ่มเซลล์หลายชนิด เป็นเนื้อเยื่อที่ทำหน้าที่ในการลำเลียงน้ำและอาหาร แบ่งออกเป็น 2 กลุ่ม คือ

1. ไซเลม (xylem)
เป็นเนื้อเยื่อที่มีหน้าที่เกี่ยวกับการลำเลียงน้ำ อินทรีย์สารและวัตถุดิบซึ่งเป็นสารละลาย รวมทั้งแร่ธาตุต่าง ๆ จากรากขึ้นไปสู่ส่วนบนของลำต้น xylem มักจะอยู่คู่กับ phloem ซึ่งเป็นท่อลำเลียงอาหารเสมอ เรียกรวมกันว่าเนื้อเยื่อลำเลียง (vascular tissue) xylem            
จะประกอบไปด้วยเนื้อเยื่อต่อไปนี้ ได้แก่

        1) เทรเคียรีเอลิเมนต์ (Tracheary elements) 
ทำหน้าที่ลำเลียงน้ำและธาตุอาหาร ประกอบด้วย
- เทรคีต (Tracheid) มีรูปร่างยาวหรือเป็นเหลี่ยมยาว         ปลายค่อนข้างแหลมทั้งสองข้าง ไม่มีผนังด้านปลาย       (end wall) พบในพืชทุกชนิดที่มีท่อลำเลียง
- เวสเซล (Vessel) มีผนังด้านปลายที่ชัดเจน อาจตัดตรง หรือเอียง พบเฉพาะในพืชมีดอกเท่านั้น

       2) ไซเลมพาเรงคิมา (xylem parenchyma) เป็นเซลล์ที่มีชีวิต รูปร่างคล้ายพาเรงคิมาทั่วไป ทำหน้าที่สะสมอาหารจำพวกแป้ง น้ำมัน ผลึกและสารอื่น ๆ นอกเหนือจากการทำหน้าที่ลำเลียงน้ำและธาตุอาหารไซเลมพาเรงคิมาบางกลุ่มอาจเรียงตัวขนานกับรัศมีของลำต้นและราก เรียกว่า ไซเลมเรย์ (xylem ray)ทำหน้าที่ลำเลียงน้ำและธาตุอาหารไปยังด้านข้างของลำต้นและราก

       3) ไซเลมไฟเบอร์ (xylem fiber) เป็นเซลล์ขนาดสั้น ผนังหนา ปลายแหลม อาจมีผนังกั้นเป็นห้อง ๆ ทำหน้าที่ช่วยให้ความแข็งแรงแก่พืชสำหรับพืชพวกจิมโนสเปิร์มและเฟิร์นพบเฉพาะเทรคีด และ ไซเลมพาเรงคิมาเท่านั้น

2. โฟลเอ็ม (Phloem)
เป็นเนื้อเยื่อที่มีหน้าที่เกี่ยวกับการลำเลียงอาหารของพืชซึ่งเป็นผลิตผลที่ได้จากการสังเคราะห์ด้วยแสง และอยู่ติดกับไซเล็มเสมอประกอบด้วยเซลล์มีหลายชนิดเช่นเดียวกับ ไซเล็มประกอบด้วย

        1) เซลล์หลอดตะแกรง (sieve tube member) เรียงต่อเป็นท่อยาว ลำเลียงอาหารปลายเซลล์มีรูพรุน เรียกแผ่นตะแกรง (sieve plate) เป็นทางให้ไซโตพลาสซึมภายในติดต่อกัน

        2) เซลล์ประกบ (companion cell) ทำหน้าที่ช่วยเหลือเซลล์หลอดตะแกรงในการลำเลียงอาหาร โดยเฉพาะเมื่อเซลล์มีอายุมากขึ้น

        3) phloem parenchyma ทำหน้าที่ช่วยสะสมอาหารและอินทรียสารเช่น เม็ดแป้ง แทนนิน เรซินและน้ำมัน เป็นต้น ตลอดทั้งทำหน้าที่ในการลำเลียงอาหารและช่วยเสริมสร้างความแข็งแรงให้แก่พืชในพืช  ที่มีการเจริญเติบโตทุติยภูมิจะพบโฟลเอ็มพาเรงคิมาเรียงตัวในแนวขนานกับรัศมีของลำต้นและราก

        4) โฟลเอ็มไฟเบอร์ (phloem fiber) ทำหน้าที่ช่วย เสริมความแข็งแรงแก่ท่ออาหาร

**Comment by ThewBear** [comment]
หน้านี้เฉพาะ Epidermis อย่างเดียว ต้องการให้เป็นข้อมูลเจาะลึกเฉพาะ Epidermis เลย

**Comment by mantayonpiam** [comment]
# epidermis
เป็นเนื้อเยื่อถาวรเชิงเดี่ยว กำเนิดมาจากชั้น protoderm มักเรียกกันว่า เนื้อเยื่อผิว เมื่อมีการเจริญขั้นที่สอง (secondary growth) เนื้อเยื่อ epidermis จะสลายไป เพราะมีชั้นของ cork ที่เกิดขึ้นใต้ epidermis เจริญดันออกมา

เซลล์เรียงแถวเดียวเบียดกันแน่นไม่มีช่องว่างระหว่างเซลล์ ผนังเซลล์บางด้านนอกมักหนากว่าด้านในเพราะมีสารคิวติน(Cutin)มาเคลือบ ผิวด้านนอกมีสารขี้ผึ้งพวกคิวตินฉาบอยู่ช่วยป้องกันการระเหยของน้ำ เรียกว่า cuticle 
![Cell](epidermisCell)
เอพิเดอร์มิสบางเซลล์มีการเปลี่ยนแปลงไปทำหน้าที่พิเศษ เช่น
               - เปลี่ยนแปลงไปเป็นเซลล์คุม (Guard cell) 
![Guardcell](epidermisGuardcell)
               - เปลี่ยนแปลงไปเป็นขนราก (Root hair)
![Roothair](epidermisRoothair)
               - เปลียนแปลงไปเป็นเซลล์ขน (Trichome)
![Trichome](epidermisTrichome)

เอพิเดอร์มิสปกติจะไม่มีคลอโรพลาสต์ยกเว้นในเอพิเดอร์มิสที่เปลี่ยนแปลงไปเป็นเซลล์คุมจะพบ คลอโรพลาสต์กระจายอยู่ทั่วเซลล์

## บริเวณที่พบ
อยู่ชั้นนอกสุดของทุกส่วนของพืชที่มีการเจริญเติบโตในขั้นต้น (primary growth) 

## หน้าที่ epidermis 
ช่วยป้องกันอันตรายให้แก่เนื้อเยื่อที่อยู่ภายใน และเสริมความแข็งแรง ช่วยป้องกันการระเหยและการคายน้ำ เกี่ยวกับการคายน้ำแลกเปลี่ยนแก๊ส สะสมน้ำและสารที่ได้จากmetabolism เกี่ยวกับการสังเคราะห์แสง การขับของเสียหรือสร้างเซลล์ใหม่ปกคลุมเมื่อมีบาดแผล ช่วยดูดซึมน้ำและแร่ธาตุ โดยเฉพาะอย่างยิ่งทางขนราก

**Comment by ThewBear** [comment]
@mantayonpiam ขอสรุปสั้นๆ เช่น
## บริเวณที่พบ
* ผิวนอกของลำต้น
## ประเภท
* Permanent tissue

**Comment by ThewBear** [comment]
Closed by [commit 58e3ddc](../commit/58e3ddcf40f9183c41cd21e48c05ef8a6d2d59aa)
