### ISSUE TITLE
เพิ่มหน้า Tissue/Cortex

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#4]
ต้องการข้อมูลของ Cortex เช่น
* ประกอบด้วย Parenchyma etc..
* ในราก Cortex กว้าง ในลำต้น Cortex แคบ

**Comment by mantayonpiam** [comment]
# cortex
เป็นอาณาเขตระหว่างชั้น epidermis และ stele ประกอบด้วยเนื้อเยื่อพาเรงคิมา ทำหน้าที่สะสมน้ำและอาหารเป็นส่วนใหญ่ และพบเนื้อเยื่ออื่นๆ เช่น
chlorenchyma ทำหน้าที่ช่วยในกระบวนการสังเคราะห์ด้วยแสง
aerenchyma ทำหน้าที่เกี่ยวข้องกับการสะสมอากาศ  โดยเฉพาะพืชน้ำ
collenchyma เพิ่มความแข็งแรงให้แก่ลำต้น
sclerenchyma(fiber) ให้ความแข็งแรงแก่ลำต้น
![Structure](cortexStructure)

ในรากชั้นในสุดของ cortex จะเห็นเป็นเซลล์เรียงแถวเดียวเรียก เอนโดเดอร์มิส (Endodermis) ซึ่งจะมีสารซูเบอรินมาสะสมเป็นแถบเรียกแถบ แคสพาเรียนสตริพ (Casparian strip) เมื่ออายุมากขึ้นจะมีลิกนินมาสะสมเพิ่ม เห็นชัดเจนในพืชใบเลี้ยงเดี่ยว แต่จะมีบางช่วงที่เซลล์มีผนังบางแทรกอยู่ในชั้นนี้และจะเป็นบริเวณที่อยู่ตรงกับแนวของxylem
![Endodermis](cortexEndodermis)
![CasparianStrip](cortexCasparianStrip)

โดยในรากชั้น cortex จะกว้างกว่าชั้น cortex ของลำต้น
![RootMonocot](cortexRootMonocot)
![StemMonocot](cortexStemMonocot)
![RootDicot](cortexRootDicot)
![StemDicot](cortexStemDicot)

**Comment by ThewBear** [comment]
Closed by [commit 58e3ddc](../commit/58e3ddcf40f9183c41cd21e48c05ef8a6d2d59aa)
