### ISSUE TITLE
เพิ่มหน้า Tissue/Stele

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#5]
ต้องการข้อมูลของ Stele เช่น
* ประกอบด้วย Vascular bundle, Xylem, Phloem etc..
* ในราก Stele แคบ ในลำต้น Stele กว้าง

**Comment by mantayonpiam** [comment]
# stele 
เป็นบริเวณที่อยู่ถัดจากชั้น endodermisเข้าไป 
stele ในรากจะแคบกว่าชั้น cortex โดยประกอบด้วยชั้นต่างๆดังนี้
![Structure](steleStructure)

## pericycle
เป็นเซลล์ผนังบางขนาดเล็ก 1-2 แถว พบเฉพาะในรากเท่านั้น เป็นแหล่งกำเนิดของรากแขนง ( secondary root )
![Pericycle](stelePericycle)

## vascular bundle 
กลุ่มของเนื้อเยื่อที่ทำหน้าที่เกี่ยวข้องกับการลำเลียง ประกอบด้วย xylem อยู่ตรงใจกลางเรียงเป็นแฉกโดยมี phloem อยู่ระหว่างแฉก สำหรับพืชใบเลี้ยงคู่ต่อมาจะเกิดเนื้อเยื่อเจริญ vascular cambium คั่นระหว่าง xylem กับ phloem ในรากของพืชใบเลี้ยงคู่มักมี 4 แฉก ส่วนรากของพืชใบเลี้ยงเดี่ยวมักมีจำนวนแฉกมากกว่า
![VascularMonocotRoot](steleVascularMonocotRoot)
![VascularDicotRoot](steleVascularDicotRoot)

## pith 
เป็นบริเวณตรงกลางราก ทำหน้าที่ในการสะสมสารต่างๆ เห็นได้ชัดเจนในรากพืชใบเลี้ยงเดี่ยว ส่วนใหญ่เป็นเนื้อเยื่อพาเรงคิมาส่วนรากพืชใบเลี้ยงคู่ตรงกลางมักเป็น xylem
![PithRoot](stelePithRoot)

ในลำต้นจะไม่มีเนื้อเยื่อ endodermis  ทำให้ชั้นสตีลในลำต้นแบ่งแยกออกจากชั้นคอร์เทกซ์ได้ไม่ชัดเจน
- vascular bundle ของพืชใบเลี้ยงคู่ประกอบด้วย กลุ่มเนื้อเยื่อลำเลียงอาหาร(phloem)เรียงตัวอยู่ทางด้านนอกและกลุ่มเนื้อเยื่อลำเลียงน้ำ(xylem)เรียงตัวอยู่ทางด้านในหรือด้านที่ติดกับ pith  ระหว่าง xylem กับ phloem จะมีเนื้อเยื่อเจริญที่เรียกว่า vascular  cambium คั่นกลางอยู่ทำหน้าที่แบ่งเซลล์เพื่อให้กำเนิด xylem และ phloem
![VascularMonocotstem](steleVascularMonocotstem)
![VascularDicotStem](steleVascularDicotStem)
![Cambium](steleCambium)

- pith  ในลำต้นของพืชใบเลี้ยงคู่บางชนิดเนื้อเยื่อในส่วนนี้อาจสลายไปกลายเป็น ช่องกลวงกลางลำต้น  เรียกว่า  pith cavity
![PithCavity](stelePithCavity)

**Comment by ThewBear** [comment]
Closed by [commit 58e3ddc](../commit/58e3ddcf40f9183c41cd21e48c05ef8a6d2d59aa)
