### ISSUE TITLE
เพิ่มหน้า Tissue/Vascular bundle

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#7]
องค์ประกอบโดยรวมของ Vascular bundle มีลิงก์เชื่อมไป xylem phloem etc.

**Comment by mantayonpiam** [comment]
# vascular bundle  
หมายถึงกลุ่มของเนื้อเยื่อที่ทำหน้าที่เกี่ยวข้องกับการลำเลียง ประกอบด้วย กลุ่มเนื้อเยื่อลำเลียงอาหาร(phloem) และกลุ่มเนื้อเยื่อลำเลียงน้ำ(xylem)
![Cell](vascularBundleCell)
ภายในเนื้อเยื่อ vascular bundle ของพืชใบเลี้ยงคู่ประกอบด้วย phloem เรียงตัวอยู่ทางด้านนอกและ xylem เรียงตัวอยู่ทางด้านในหรือด้านที่ติดกับ pith  ระหว่าง xylem กับ phloem จะมีเนื้อเยื่อเจริญที่เรียกว่า vascular  cambium คั่นกลางอยู่ทำหน้าที่แบ่งเซลล์เพื่อให้กำเนิด xylem และ phloem
![Dicot](vascularBundleDicot)

พืชใบเลี้ยงเดี่ยว ส่วนของ xylem, phloem จะเรียงตัวกันมองคล้ายๆใบหน้าคน มีส่วนของ vessel อยู่บริเวณคล้ายดวงตา ส่วน phloem อยู่บริเวณคล้ายหน้าผาก xylem และ phloem จะถูกล้อมรอบด้วยเนื้อเยื่อ parenchyma หรืออาจเป็น sclerenchyma และเรียกเซลล์ที่มาล้อมรอบนี้ว่า bundle sheath
vascular bundle ของพืชใบเลี้ยงเดี่ยวส่วนใหญ่ไม่พบเนื้อเยื่อเจริญ vascular cambium ยกเว้นหมากผู้หมากเมีย และพืชตระกูลปาล์ม
![Monocot](vascularBundleMonocot)

**Comment by ThewBear** [comment]
Closed by [commit deb3111](../commit/deb3111e58f75e21b0ae778098d50b08e57a7201)
