### ISSUE TITLE
เพิ่มหน้า Tissue/Phloem

### ISSUE THREAD

**Issue by ThewBear** [ThewApp/Biology-Plant#9]
เขียนบรรยายรายละเอียด

**Comment by mantayonpiam** [comment]
# ท่อลำเลียงอาหาร (phloem)
เป็นเนื้อเยื่อที่ทำหน้าที่ลำเลียงอาหารและสร้างความแข็งแรงให้แก่ลำต้นพืช โดยลำเลียงจากใบไปสู่ส่วนต่างๆของพืช เพื่อใช้ในการสร้างพลังงานของพืช ประกอบด้วยเซลล์ 4 ชนิด ดังนี้

## ซีฟทิวบ์เมมเบอร์ (sieve tube member) 
เป็นเซลล์ที่มีรูปร่างเป็นทรงกระบอกยาว เป็นเซลล์ที่มีชีวิต ประกอบด้วย ช่องว่างภายในเซลล์ (vacuole) ขนาดใหญ่มาก เมื่อเซลล์เจริญเติบโตเต็มที่แนิวเคลียสจะสลายไป ผนังเซลล์มีเซลลูโลส (cellulose) สะสมอยู่เล็กน้อย ทำหน้าที่เป็นทางส่งผ่านของอาหารที่ได้จากกระบวนการสังเคราะห์ด้วยแสงของพืชไปยังส่วนต่างๆ ของลำต้นพืช
![Sievetube](phloemSievetube)

## คอมพาเนียนเซลล์ (companion cell) 
เป็นเซลล์พิเศษที่มีต้นกำเนิดมาจากเซลล์แม่เซลล์เดียวกันกับซีฟทิวบ์เมมเบอร์ เป็นเซลล์ขนาดเล็กที่มีรูปร่างผอมยาว มีลักษณะเป็นเหลี่ยม ส่วนปลายแหลม เป็นเซลล์ที่มีชีวิต มีไซโทพลาซึมที่มีองค์ประกอบของสารเข้มข้นมาก มีเซลลูโลสสะสมอยู่ที่ผนังเซลล์เล็กน้อย และมีรูเล็กๆ เพื่อใช้เชื่อมต่อกับซีฟทิวบ์เมมเบอร์ ทำหน้าที่ช่วยเหลือซีฟทิวบ์เมมเบอร์ให้ทำงานได้ดีขึ้นเมื่อเซลล์มีอายุมากขึ้น 
![Companion](phloemCompanion)

## โฟลเอ็มพาเรงคิมา (phloem parenchyma) 
เป็นเซลล์ที่มีชีวิต มีผนังเซลล์บาง มีรูเล็กๆ ที่ผนังเซลล์ โฟลเอ็มพาเรงคิมาทำหน้าที่สะสมอาหารที่ได้จากกระบวนการสังเคราะห์ด้วยแสงของ พืช ลำเลียงอาหารไปยังส่วนต่างๆ ของพืช และเสริมความแข็งแรงให้กับท่อลำเลียงอาหาร
![Parenchyma](phloemParenchyma)

## โฟลเอ็มไฟเบอร์ (phloem fiber) 
มีลักษณะคล้ายกับไซเล็มไฟเบอร์ มีรูปร่างลักษณะยาว มีหน้าตัดกลมหรือรี ทำหน้าที่ช่วยเสริมความแข็งแรงให้กับท่อลำเลียงอาหารและสะสมอาหารให้แก่พืช
![Fiber](phloemFiber)

**Comment by ThewBear** [comment]
Closed by [commit deb3111](../commit/deb3111e58f75e21b0ae778098d50b08e57a7201)
